### ISSUE TITLE
ToonCrafter flash between image transitions

### ISSUE THREAD

**Issue by fofr** [kijai/ComfyUI-DynamiCrafterWrapper#40]
I'm noticing a dulling/fading between the image transitions in ToonCrafter outputs

Example video:

https://github.com/kijai/ComfyUI-KJNodes/assets/319055/9151b6ab-9ca7-4ff8-80c5-f3418f5e1df8

Each frame (with and without last image pruning)

<img width="375" alt="Screenshot 2024-06-01 at 23 21 35" src="https://github.com/kijai/ComfyUI-KJNodes/assets/319055/192cacf7-7f9c-4d6a-b418-1ac8d0269f6c">

<img width="355" alt="Screenshot 2024-06-01 at 23 22 23" src="https://github.com/kijai/ComfyUI-KJNodes/assets/319055/97307c7d-c9d6-4186-910b-2e5787794bde">

Workflow (just a screenshot):

<img width="1322" alt="Screenshot 2024-06-01 at 23 24 49" src="https://github.com/kijai/ComfyUI-KJNodes/assets/319055/36679a5b-359c-40fd-adb1-97950a30d217">

**Comment by kijai** [comment]
This is due to the encoder/decoder ToonCrafter uses is designed to be used with xformers, I couldn't get it fully working without it and that first/last frame being gray mush is the exact result that happens when xformers is not used. 

You can either install it (pip install xformers --no-deps), or alternatively simply replace the decoder node with a normal comfy VAE decoder, using any 1.5 VAE, which works without xformers with slight quality hit.

**Comment by fofr** [comment]
Thank you for the explainer, installing xformers fixed it 🙏
