### ISSUE TITLE
color deviation in 512 interpolation

### ISSUE THREAD

**Issue by cheezecrisp** [kijai/ComfyUI-DynamiCrafterWrapper#83]
There is a color deviation issue with interpolation using 512_interp model. When applying interpolation operation, the first&last few frames of DynamicrafterBatchInterploation node are brghter, and the last few frames of DynamicrafterI2V node are darker. Is it a problem of model itself? Any way to improve it?

**Comment by DevouredByBeef** [comment]
I've noticed the exact same issue with the  `DynamiCrafterI2V` node creating darker final frames with interpolation, compared with the version of the node at the end of March (last time I used the interpolation model).

Tested this with the same model I used in March without the color degradation, so the problem isn't with the model itself. I'd say this might have stemmed from the recent refactor, but I haven't had a chance to comb through the commits since March.

Example for testing purpose, using defaults:
| Image 1 | Image 2 |
|:--:|:--:|
|![ball1](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/144713652/b8b242aa-8768-41b8-adca-baff6a32c7df) | ![ball2](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/144713652/f3c772bc-b7a1-43de-8b98-71161ce95f52) |

| First Frame | Last Frame |
|:--:|:--:|
|![dyn_00018_000001](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/144713652/11fcde69-901c-4f24-8eca-53b2bb8b5343)|![dyn_00018_000016](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/144713652/358f5001-5894-418c-bb53-db9a6e217d9a)|

<details>
  <summary>Video Output</summary>

https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/144713652/0ce1769c-66cd-46c1-b1bd-1ab520a55671


</details>

While this example only shows a single frame effected, images with more color variation usually result in a more gradually drop in brightness.

**Comment by DevouredByBeef** [comment]
Ok found the commit at which issues started, was June 4th:
https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/commit/886e095e945ca495c1bedd78acafb496ec17604b

Prior to this the final brightness levels are consistent

**Comment by kijai** [comment]
Ok, fixed.

I do recommend moving onto the ToonCrafterInterpolation node, even with the old model, it has more features that I'm not gonna bring to the old nodes, might even deprecate them at some point as it's getting too many to maintain for no real benefit besides backwards compability.
